(defun wander (obj)
  (move obj (random-direction)))

(defun smart-wander (obj)
  (let ((initial-index (random 8)))
    (do ((index initial-index (mod (1+ index) 8))
	 (times-round 0 (if (= initial-index index)
			    (1+ times-round)
			    times-round))
	 (direction (nth initial-index +directions+)
		    (nth index +directions+)))
	((or (and (= initial-index index)
		  (= times-round 1))
	     (and (not (solid (vec+ (pos obj) direction)))
		  (< (movement-cost (vec+ (pos obj) direction)) 4)))
	 (move obj direction)))))

(defun no-idle (obj))
