(load "~/quicklisp/setup.lisp")
(ql:quickload :trivial-raw-io)

(load "utils.lisp")
(load "colors.lisp")
(load "class-definitions.lisp")
(load "bsp-dungeon.lisp")
(load "game-engine.lisp")
(load "codex.lisp")
(load "game.lisp")
